### ISSUE TITLE
snis_launcher refers to DESTDIR

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#194] opened 2019-02-13 21:33 UTC
When building the package for ArchLinux, I do `make PREFIX="/usr" DESTDIR="$pkgdir" install`

This should install files into DESTDIR/PREFIX but make them behave as if installed in PREFIX, basically.

In the current situation the DESTDIR is set in snis_launcher, which causes the package build tool to complain:

> ==> ATTENTION : Le paquet contient une référence à $pkgdir                     
> usr/bin/snis_launcher

And indeed snis_launcher (which is inside the built package) contains a path to my home folder which other users of the package will not have.

**Comment by smcameron** [comment] 2019-02-13 21:45
I am pretty sure I do not understand how DESTDIR and PREFIX are meant to be used well enough to correctly implement it.

**Comment by MCMic** [comment] 2019-02-13 21:49
PREFIX is where the game will be in the end. It usually defaults to /usr/local and is set to /usr when packaging.
It is passed to make at build time so it can be used in the code.

DESTDIR is only where to put the files, it is passed only to make install target, and should not appear in the code.
Basically this should only be used by make to know where to put the files. In the package building case, it is set to a folder which is then archived as the package content, and when the package is installed files end up in PREFIX.
When installing by hand DESTDIR may be used to check what will be installed before applying to the system. (or you may want to use DESTDIR=/tmp and then cp the files yourself if you want to double check what gets installed).

**Comment by MCMic** [comment] 2019-02-13 21:52
The only file where my packaging test complains is snis_launcher so I think the rest is already correct.

And looking at snis_launcher content I would expect removing `DESTDIR` and replacing `${DESTDIR}/${PREFIX}` occurences by `${PREFIX}` should be enough

**Comment by smcameron** [comment] 2019-02-13 21:57
There's an awk thing in the Makefile too.

Can you try this patch? 

[fix-destdir.txt](https://github.com/smcameron/space-nerds-in-space/files/2862367/fix-destdir.txt)

**Comment by MCMic** [comment] 2019-02-13 22:16
The warning is gone and snis_launcher does work after install. I get failed bridge verification errors but I’m not sure why and if it is related.

**Comment by smcameron** [comment] 2019-02-13 22:26
The failed bridge verification errors are probably related to snisdb/ which is where it stores data about your ship, including a hash of the password.

Probably it's not finding it, or it created a new empty one because you're in a different directory than usual, but you didn't check CREATE SHIP on the login screen.

something along those lines. https://smcameron.github.io/space-nerds-in-space/#bridgeverification

snis_multiverse is the one that deals with snisdb.  It looks like it expects snisdb/ to be in the current directory.  I should probably make that more configurable.

**Comment by smcameron** [comment] 2019-02-16 17:51
If it wasn't clear, I am pretty sure it's working as intended.

**Comment by smcameron** [comment] 2019-02-17 15:56
Ha. "I am pretty sure it's working as intended."  Famous last words. So I tried a play session at HackRVA last night and *snis_launcher was completely broken*.  I'm at a loss as to how that slipped through, but it was definitely broken. Hacked a "fix" in to make things go: 0c1e8161d48e9aef460dd9cd26561021b228cc28

But need a real fix.

**Comment by MCMic** [comment] 2019-02-17 17:20
I bumped into the same thing and had the same fix, I think default PREFIX should indeed be "." and not "".

**Comment by MCMic** [comment] 2019-02-17 17:21
(Either that or you have to handle properly empty PREFIX and not add a "/" in that case but I think it’s more complicated without any benefit)
From what I’ve seen only snis_launcher is concerned by this problem.

**Comment by smcameron** [comment] 2019-03-01 12:53
Closing this as I think it's working correctly.

**Closed by smcameron** 2019-03-01 12:53 UTC
