### ISSUE TITLE
Lua scripting missing features

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#185] opened 2019-01-29 21:51 UTC
Hello,

I’m working on writing a new mission script for the game.

I’m trying to do it on my own so that you may play the mission once it’s ready.

I’d like to do the following things from the lua code:

1. Add a passenger waiting at a station
2. Board a passenger to the player ship

**Comment by smcameron** [comment] 2019-01-29 22:05
Glancing through lua-api.txt I don't think I have a way to do those things
at the moment.

Adding a lua-callable function to add a passenger waiting at a station
shouldn't be too hard, there's a passenger[] array in snis_server.c and
each passenger has a name, location (starbase ID) and destination (starbase
ID) and fare.  There are a fixed number of passengers though, so it will
basically need to grab one of the existing passengers and set all the
values.

"Boarding" the passengers is simply a matter of changing the passenger
location to be the ID of the player ship.

So, I guess the lua calls could look something like:

n = create_passenger(name, location, destination, fare);

n is a number identifying the passenger
name is a string
location is the ID of the starbase the passenger is currently on.
destination is the ID of the starbase the passenger wants to go to
fare is how much money the player will get

board_passenger(n, ship_id);

n is the value returned from create_passenger()
ship_id is the ID of the player ship.

How does that sound?

-- steve








-- steve

**Comment by smcameron** [comment] 2019-01-30 03:39
Ok, I added 3 new functions, and 2 events:

New functions:

create_passenger(n, name, location, destination, fare) -- set a passenger's
name, location,
        destination and fare. Parameters:
        n: the passenger number, which should be between 0 and 80.
        name: is the name of the passenger, a string, no longer than 49
characters.
        location: the ID of a starbase to move the passenger to.
        destination: the ID of a starbase to which the passenger wants to
travel.
        fare: The fare the player should get upon delivering the passenger.

set_passenger_location(n, location) -- sets passenger location
        Parameters:
        n: the passenger number (between 0 and 80, inclusive).
        location: The ID of the starbase or player ship where the passenger
should be located.

get_passenger_location(n) -- gets passenger location
        Parameters:
        n: the passenger number (0 - 80).
        Returns:
        ID of the starbase or player ship where the passenger is currently
located.


New events (see register_callback() function in lua-api.txt)

        "passenger-disembarked"
                Arguments are the passenger number (0 - 80) and id of the
destination starbase.
        "passenger-ejected"
                Arguments are the passenger number (0 - 80) and id of the
starbase at which
                the passenger was ejected.

**Comment by smcameron** [comment] 2019-01-30 03:40
Oh, I haven't tested that code yet.  It should work (famous last words).
Let me know if you find anything not right about it.

-- steve

**Comment by MCMic** [comment] 2019-01-30 11:23
add_planet do not respect the radius I give it, because it randomly selects a planet type which has different radius min and max.

So:

1. I think it would be good to be able to tell which planet type we want to create
2. I should have a way to get the planet radius after creating it, to be able to put a starbase near it (currently my starbase end up inside the planet in some cases)
3. Better would be access to planet details to be able to set government and such for back story
4. When radius is < min it should be set to min and when > max set to max, to avoid to deviate too much from asked radius. Currently if you give out of bound radius you get random radius (and you cannot know bounds because they depend on autochosen type). Maybe a special value like 0 radius for random radius would still be usefull.

**Comment by smcameron** [comment] 2019-01-30 13:46
Thanks for the feedback and suggestions. They all seem reasonable. Some of this might be a little difficult, so take a little awhile.

For example, for awhile some planet traits were determined by properties of the Object ID (a 32 bit int that you have no control over). For example whether a planet had a ring was controlled by some expression like ((object_id % 4) == 0), or whether a planet was a gas giant, earthlike, or rocky was controlled by something like ((object_id % 3) == 0) plus whether any appropriate textures were present in the current solar system assets.  In retrospect, using the object_id in this way was a mistake.  I think I have fixed some of that nonsense, but I don't remember if I fixed all of it.  Fixing it requires changing the protocol to transmit this information in another way and some bits in the rendering code (which is not that big a deal, but makes things a little more complicated than they otherwise would be.)

IIRC, the government back story is procedurally generated and is not stored or transmitted from server to client, instead only a seed number is stored and transmitted and used by the procedural generation to recreate the back story on the fly as needed.  So currently, there is no place to store or transmit such a story.  Not to say it couldn't be done though, the attach_science_text() lua function is a similar case, and that works.

**Comment by MCMic** [comment] 2019-01-30 19:08
create_passenger and set_passenger_location seems to work fine :+1: 

I tested the attach_science_text on planets, indeed it adds a secondary text in white, I expected to replace the green text.
Also science text appears in SRS view, that’s a bit weird.
It would be cool if the generated text is the default value for science text and we can modify it from lua.

BTW, when scanning a planet, why does it say type:unknown on the right while on the left (detail view), it says Type: gas giant (for example) ?

**Comment by smcameron** [comment] 2019-01-30 20:36
So, iirc, the attach_science_text() can attach text to any object, while
only planets have the specially generated planet description text.  I could
allow replacement of the generated text for planets but I think this would
be another function besides attach_science_text.

I think the attach_science_text appears in SRS because typically this is
used to convey some information actually relevant to some mission script,
and if you don't do something unusual like that, then players don't notice
the text at all. They become accustomed to the generated text containing no
really useful information, and so do not read it -- if you merely replace
it, they will never see your replacement text, because they assume whatever
text is there is unimportant.

The type on the right hand is the type of object (e.g. what kind of ship,
whether it's and asteroid, planet, cargo container, etc.  It says "unknown"
because this switch statement does not have everything in there that it
should:
https://github.com/smcameron/space-nerds-in-space/blob/master/snis_client.c#L14970

-- steve

**Comment by MCMic** [comment] 2019-01-30 22:41
> I think the attach_science_text appears in SRS because typically this is
> used to convey some information actually relevant to some mission script,
> and if you don't do something unusual like that, then players don't notice
> the text at all. They become accustomed to the generated text containing no
> really useful information, and so do not read it -- if you merely replace
> it, they will never see your replacement text, because they assume whatever
> text is there is unimportant.

Ok, I get that. In my case I just wanted to provide some backstory for curious players, not essential to the mission. Not that important for now.

> The type on the right hand is the type of object (e.g. what kind of ship,
> whether it's and asteroid, planet, cargo container, etc.  It says "unknown"
> because this switch statement does not have everything in there that it
> should:
> https://github.com/smcameron/space-nerds-in-space/blob/master/snis_client.c#L14970

Hum, as for ships it does say which kind of ship it is in there, I think it should do the same for planets and the type should be removed from the left part.

**Comment by MCMic** [comment] 2019-01-30 22:47
@smcameron How much distance does maximum warp covers?

**Comment by smcameron** [comment] 2019-01-31 01:40
Could you try the following patch and see if it works to allow lua to create planets of specified type?

[allow-lua-to-specify-planet-type-with-add-planet.txt](https://github.com/smcameron/space-nerds-in-space/files/2815334/allow-lua-to-specify-planet-type-with-add-planet.txt)

**Comment by smcameron** [comment] 2019-01-31 01:45
> @smcameron How much distance does maximum warp covers?

300000 units. See https://github.com/smcameron/space-nerds-in-space/blob/master/snis_server.c#L19819

```
	if (enough_oomph) {
		wfactor = ((double) o->tsd.ship.warpdrive / 255.0) * (XKNOWN_DIM / 2.0);
		quat_rot_vec(&warpvec, &rightvec, &o->orientation);
		/* At this point, warp[xyz] holds coordinates we are warping TO */
		bridgelist[b].warpx = o->x + wfactor * warpvec.v.x;
		bridgelist[b].warpy = o->y + wfactor * warpvec.v.y;
		bridgelist[b].warpz = o->z + wfactor * warpvec.v.z;
		o->tsd.ship.warp_time = PLAYER_WARP_SPINUP_TIME;
}
```

XKNOWN_DIM is 600000, see: https://github.com/smcameron/space-nerds-in-space/blob/master/snis.h#L34

**Comment by MCMic** [comment] 2019-01-31 12:13
Adding gas giant and earthlike works fine with the patch, but not adding rocky planet.
But it seems rocky planets cannot be added in default starsystem?

**Comment by smcameron** [comment] 2019-01-31 14:55
Correct.

It works like this:  It picks a random number, modulo the number of
planet-textures in the current solarsystem, then looks for the first
planet-texture of the requested type starting with that modulo'ed random
number going forward (starting at the beginning if it hits the end) until
it either finds one of the requested type, or searches through all of
them.  If it searches through all of them without finding the requested
type, it returns the last one it looked at (which will be a random one,
since it started looking on a random one.)

-- steve

**Comment by smcameron** [comment] 2019-01-31 15:03
The reason you cannot have rocky planets in the default solarsystem is because it is the first one I made, and I hadn't yet made the tools to create rocky planet textures at that time and didn't have any normal maps.  It's also why the earthlike planet in the default solar system is kind of ugly, and why it uses the same earthlike planet texture twice -- I hadn't yet figured out how to make them less ugly. And snis_client actually complains about the lack of normal maps for the earthlike planets in the default solar system.

```
Reading solarsystem specifications....//share/snis/solarsystems/default/assets.txt: planet texture ../../textures/planet-texture4- is type earthlike but has no normalmap
.//share/snis/solarsystems/default/assets.txt: planet texture ../../textures/planet-texture4- is type earthlike but has no normalmap
```

**Comment by smcameron** [comment] 2019-01-31 15:18
I have now committed this with a couple small tweaks from the patch I sent you to more carefully sanitize the planet type value.

13c705ec6bc461ad26dabdeb6174cda5863558e1

**Comment by smcameron** [comment] 2019-02-01 14:58
> Hum, as for ships it does say which kind of ship it is in there, I think it should do the same for planets and the type should be removed from the left part.

Done. 2c9e82d97405d6dd6a9986051104c2669a4efb59

**Comment by MCMic** [comment] 2019-02-01 17:33
Thanks!

**Comment by smcameron** [comment] 2019-02-01 18:57
Now you can set a custom planet description with set_planet_description(planet_id, "blah blah blah... "); from Lua.  d8b573cf9e00459ffea11aaf87f324215ff58fe1

**Comment by smcameron** [comment] 2019-02-01 19:51
Now you can set planet government, economy, security, and tech level from Lua.  8ef7f3dc60c05c066279bf8b6d08e1f2852e75d5

**Comment by smcameron** [comment] 2019-02-02 04:48
Uh, didn't mean to close this, hit the close button by accident, so I re-opened it.  That being said, I do think I have implemented all the requested features, so if you agree, feel free to close it. Or, if you don't agree with that, describe why, and we'll proceed from there.

**Comment by MCMic** [comment] 2019-02-02 12:46
Thanks, the new functions for setting planets attributes and description work fine!

**Comment by MCMic** [comment] 2019-02-02 16:34
There is a problew with planet descriptions.
I set the description for two planets, but the second one does not get the description I set.

Even more, If I scan the first one and then the second one it shows the description for the first one. (But if I do not scan the first one I get generated text)

**Comment by smcameron** [comment] 2019-02-02 17:18
Interesting.  I've duplicated the behavior you describe here.

**Comment by smcameron** [comment] 2019-02-02 18:33
Ok, I think it's fixed by 5ad86ed5ddf4d4ddc843831f858f98792789cbb5 and by c5c51b0e4be58dee31750c0bbaf228d146b318b5

**Comment by MCMic** [comment] 2019-02-02 22:56
With these patches, I see planets in LRS but cannot select them, they get selected and deselected right away.

I get that there attributes may not be scannable from too far away, but if I see them I should be able to select them for the pilot to fly toward them no?

**Comment by smcameron** [comment] 2019-02-03 01:54
Hmm. I need to work on it.  The problem is the only test on the client
currently is if the 2D position on the screen is within a fixed 2D radius
of 100 pixels of the ship, essentially, while on the server a 3D range test
is done that takes into account power of the sensors and the beam angle.
So the client selects, requests selection on the server, and the server
rejects it because there's not enough power the beam has been off it for
too long.

I could try to do the same test on the client, however, I am not sure I
actually have all the information I need to do so on the client... or maybe
I do, but it's a complex test.

Need to think about it.

**Comment by smcameron** [comment] 2019-02-03 02:08
Or, maybe it's a little simpler than that.

If I have a squared distance, and I want 4x that distance, I need to multiply the square by 16, not by 4.

You may still see some things that are very very far away that select then deselect though... or it may happen if science power is low, since the client does not take science power into account when determinine what you can attempt to select.  So I should still work on that.

But this should help some: 0036ec13353f8a87a83925fa91c4918d3107dfb7

**Closed** 2019-02-14 21:01 UTC
